apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: demo-repo-123234343431a
  annotations:
    github.com/project-slug: super-awesome-org/demo-repo-123234343431a
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  lifecycle: experimental
  owner: backstage
